name: Pair_Extraordinaire

on: # workflow_dispatch ## This is used to run workflow on demand
  schedule:
    - cron: '0 */8 * * *' # This runs at every eight hour, each day.
    # (At minute 0 past every 8th hour.)
# * is a special character in YAML, so you have to quote this string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content
        with:
          token: ${{ secrets.EXTRAORDINAIREPAT }} # Use EXTRAORDINAIREPAT secret for authentication

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed

      - name: install python packages # install needed the packages needed
        run: |
          python -m pip install --upgrade pip
      #          pip install -r requirements.txt

      - name: execute py script # run main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Use GITHUB_TOKEN secret for authentication
          # in case EXTRAORDINAIREPAT is not available
          EXTRAORDINAIREPAT: ${{ secrets.EXTRAORDINAIREPAT }} # Use EXTRAORDINAIREPAT secret for authentication
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }} # Use GIT_EMAIL secret for Author Email
        run: python main.py
